-- thực tập nhóm
-- đề tài quản lý học sinh 
CREATE DATABASE QLHOCSINH
GO

USE QLHOCSINH
GO

CREATE TABLE HOCSINH 
(
   MAHOCSINH INT  PRIMARY KEY IDENTITY(1,1),
   HOTEN NVARCHAR(50),
   GIOITINH NVARCHAR(5),
   NGAYSINH DATETIME,
   NOISINH NVARCHAR(50),
   DANTOC NVARCHAR(50),
   TONGIAO NVARCHAR(50) 
)
GO
CREATE TABLE GIAOVIEN
(
   MAGIAOVIEN INT PRIMARY KEY IDENTITY(1,1),
   HOTEN NVARCHAR(50),
   GTINH NVARCHAR(5),
   NGAYSINH DATETIME,
   NOISINH NVARCHAR(50),
   DIACHI NVARCHAR(50),
   CHUYENMON NVARCHAR(20),
   SODIENTHOAI NVARCHAR(11),
)
GO
CREATE TABLE LOP
(
   MALOP INT PRIMARY KEY IDENTITY(1,1),
   TENLOP NVARCHAR(20),
   SISO INT,
   MA_GVCHUNHIEM INT REFERENCES dbo.GIAOVIEN(MAGIAOVIEN)
)
GO
CREATE TABLE KETQUAHOCTAP
(
  MAHOCSINH INT REFERENCES dbo.HOCSINH(MAHOCSINH),
  MALOP INT REFERENCES dbo.LOP(MALOP),
  DIEMTBKY1 FLOAT,
  DIEMTBKY2 FLOAT,
  DIEMTBCANAM FLOAT,
  PRIMARY KEY(MAHOCSINH,MALOP)
)
GO
CREATE TABLE MONHOC 
(
  MAMONHOC INT PRIMARY KEY IDENTITY(1,1),
  TENMONHOC NVARCHAR(30)
)
GO

CREATE TABLE LOP_MON 
(
  MAMONHOC INT REFERENCES dbo.MONHOC,
  MALOP INT REFERENCES dbo.LOP,
  MAGIAOVIEN INT REFERENCES dbo.GIAOVIEN(MAGIAOVIEN),
  SOTIET INT,
  PRIMARY KEY(MAMONHOC,MALOP)
)
GO
CREATE TABLE BANGDIEM
(
  MAHOCSINH INT REFERENCES DBO.HOCSINH(MAHOCSINH),
  MAMONHOC INT REFERENCES dbo.MONHOC(MAMONHOC),
  HOCKY INT,
  DIEMMIENG FLOAT,
  DIEM15PHUT FLOAT,
  DIEM1TIET FLOAT,
  DIEMHK FLOAT,
  DIEMTB FLOAT,
  PRIMARY KEY(MAHOCSINH,MAMONHOC)
)
GO

CREATE TABLE ACCOUNT
(
 USERNAME VARCHAR(50) PRIMARY KEY,
 PASSWORD VARCHAR(50),
 MAGIAOVIEN INT FOREIGN KEY REFERENCES dbo.GIAOVIEN( MAGIAOVIEN),
 PHANQUYEN INT
)

go


-- cac trigger
CREATE TRIGGER [dbo].[XOAGIAOVIEN] ON [dbo].[GIAOVIEN] INSTEAD OF DELETE
AS 
    DECLARE @MAGIAOVIEN INT 
	BEGIN 
	SELECT @MAGIAOVIEN=Deleted.MAGIAOVIEN FROM Deleted
	
	UPDATE dbo.LOP SET MA_GVCHUNHIEM=NULL WHERE MA_GVCHUNHIEM=@MAGIAOVIEN
	UPDATE dbo.LOP_MON SET MAGIAOVIEN=NULL WHERE MAGIAOVIEN=@MAGIAOVIEN
	DELETE dbo.GIAOVIEN WHERE MAGIAOVIEN=@MAGIAOVIEN
	END

go
CREATE TRIGGER [dbo].[XOAHOCSINH] ON [dbo].[HOCSINH] INSTEAD OF DELETE
AS
   DECLARE @MAHOCSINH INT 
   BEGIN 
   SELECT @MAHOCSINH=Deleted.MAHOCSINH FROM Deleted
  
   DELETE dbo.BANGDIEM WHERE MAHOCSINH=@MAHOCSINH
   DELETE dbo.KETQUAHOCTAP WHERE MAHOCSINH=@MAHOCSINH
    DELETE dbo.HOCSINH WHERE MAHOCSINH=@MAHOCSINH
   END



go

CREATE trigger [dbo].[them_HS_Mon] on [dbo].[KETQUAHOCTAP] for insert as
BEGIN 
declare @mahs int , @malop int
select @mahs=inserted.MAHOCSINH from inserted
SELECT @malop=inserted.MALOP FROM inserted
insert into BANGDIEM (MAHOCSINH,MAMONHOC)
select distinct @mahs,L.MAMONHOC from KETQUAHOCTAP kq, LOP_MON l WHERE kq.MALOP=L.MALOP AND L.MALOP=@malop

UPDATE lop SET SISO=SISO+1 WHERE MALOP=@malop
END 

go

CREATE TRIGGER [dbo].[XOAMONHOC] ON [dbo].[MONHOC] INSTEAD OF DELETE  
AS 
    DECLARE @MAMONHOC INT 
	BEGIN
	SELECT @MAMONHOC=Deleted.MAMONHOC FROM Deleted
	DELETE dbo.BANGDIEM WHERE MAMONHOC=@MAMONHOC
	DELETE dbo.MONHOC WHERE MAMONHOC=@MAMONHOC
	DELETE dbo.LOP_MON WHERE MAMONHOC=@MAMONHOC
	PRINT 'đã xóa môn học có mã môn học :' +@MAMONHOC
	END

go

-- cac proc
CREATE PROC [dbo].[CAPNHATSISO](@MALOP INT)
AS 
DECLARE @SISO INT
BEGIN
SELECT @SISO = (SELECT COUNT(k.MAHOCSINH)
               FROM dbo.KETQUAHOCTAP k 
		       WHERE K.MALOP=@MALOP
			   )
print @SISO
UPDATE dbo.LOP SET SISO=@SISO WHERE MALOP=@MALOP
END


-- 
go
CREATE PROC [dbo].[themLop](@teblop VARCHAR(20),@siso INT , @magv INT)
AS
BEGIN
   INSERT dbo.LOP
           ( TENLOP, SISO, MA_GVCHUNHIEM )
   VALUES  ( @teblop, -- TENLOP - nvarchar(20)
             @siso, -- SISO - int
             @magv  -- MA_GVCHUNHIEM - int
             )
END 


go

insert ACCOUNT (USERNAME,PASSWORD,PHANQUYEN) VALUES('admin', '5F4DCC3B5AA765D61D8327DEB882CF99',1)


-------------------------------------------------------------------------------------------------------------------------------------------

-- THEM HOC SINH
INSERT HOCSINH (
HOTEN,
GIOITINH,
NGAYSINH,
NOISINH,
DIACHI,
TONGIAO) VALUES (
'NGUYEN VAN B',
'NAM',  
'2/3/1997', - 
'HA NOI',  
'HA NOI',  
 'không'
)
SELECT * FROM HOCSINH 
GO
DELETE dbo.HOCSINH 
WHERE MAHOCSINH='1' AND MAHOCSINH='2'

ALTER TABLE dbo.HOCSINH ADD DANTOC NVARCHAR(50)
GO
INSERT dbo.HOCSINH
        (MAHOCSINH, 
		HOTEN ,
          GIOITINH ,
          NGAYSINH ,
          NOISINH ,
          TONGIAO ,
          DANTOC
        )
VALUES  (
		N'Tran van b' , -- HOTEN - nvarchar(50)
          N'Nam' , -- GIOITINH - nvarchar(5)
          '1997-26-3' , -- NGAYSINH - datetime
          N'Ha Noi' , -- NOISINH - nvarchar(50)
          N'Khong' , -- TONGIAO - nvarchar(5)
          N'Kinh'  -- DANTOC - nvarchar(50)
        )

DELETE dbo.HOCSINH 
WHERE MAHOCSINH=1

GO
SELECT * FROM  dbo.HOCSINH
GO
INSERT dbo.HOCSINH( HOTEN ,GIOITINH , NGAYSINH , NOISINH ,DANTOC ,TONGIAO) VALUES( N'Doan Van A' , N'Nam' , '3-2-97' ,N'Ha Noi' , N'Kinh' ,  N'Khong')

INSERT dbo.HOCSINH VALUES  ( N'Nguyen Van A' ,N'Nam' , '1-1-1997' , N'ha noi' , N'kinh' , N'khong')

GO
DELETE dbo.HOCSINH WHERE MAHOCSINH=4

UPDATE dbo.HOCSINH SET HOTEN ='a' ,GIOITINH='Nam',NGAYSINH='1-1-1997',NOISINH='ha noi',DANTOC='kinh',TONGIAO='khong' WHERE MAHOCSINH=1
GO
INSERT dbo.MONHOC
        ( TENMONHOC )
VALUES  ( N'Toan-10'  -- TENMONHOC - nvarchar(30)
          )

insert into BANGDIEM (MAHOCSINH,MAMONHOC)
select 1 ,L.MAMONHOC from KETQUAHOCTAP kq, LOP_MON l WHERE kq.MALOP=L.MALOP AND L.MALOP=1

INSERT dbo.HOCSINH VALUES  ( N'{0}' ,N'{1}' , '{2}' , N'{3}' , N'{4}' , N'{5}')

UPDATE dbo.HOCSINH SET HOTEN ='Vu Duc Do' ,GIOITINH='Nam',NGAYSINH='11/1/1997',NOISINH='Nam Dinh',DANTOC='Kinh',TONGIAO='Khong' WHERE MAHOCSINH= 4005

go










